name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The SemVer type of the release (major / minor / patch)"
        required: true
        type: choice
        options: 
        - major
        - minor
        - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Bump version
      run: >
        echo "BUMPED_VERSION=$(
        npm version --commit-hooks false --git-tag-version false patch
        )" | tee -a $GITHUB_ENV

    - name: Checkout and push branch
      run: |
        git checkout -b bump_version_${{ env.BUMPED_VERSION }}
        git push origin bump_version_${{ env.BUMPED_VERSION }}

    - name: Create PR
      uses: actions/github-script@v5
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Bump version to ${{ env.BUMPED_VERSION }}"
              head: bump_version_${{ env.BUMPED_VERSION }},
              base: "main",
              body: "This PR bumps the version to ${{ env.bumped_tag }}, as requested by @${{ github.actor }} in https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}."
            })