name: Create Release

on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get tag
        run: |
          echo TAG=$(git log -1 --format='%B' --no-merges) | tee -a $GITHUB_ENV

      - name: Create release
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "v${{ env.TAG }}",
              name: "IPTV-ReStream v${{ env.TAG }}",
              draft: true,
              generate_release_notes: true
            })