name: Node.js CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Build using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build (Transpile)
      run: npm run build

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x, 14.x]
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Lint using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint
      run: npm run lint